chore: developer experience improvements (#529)
energywebfoundation/ssi-hub pull request #540
Opened 2022-11-15 17:51 UTC by artursudnik

This PR contains cherry-picked changes from #529 already merged [(see the commit)](https://github.com/energywebfoundation/ssi-hub/commit/21a0983e7773c704b8bb65da89aea6d39b6d94f8) to the `sandbox` branch and closed.

2022-11-16 06:12 UTC, nichonien approved these changes

2022-11-16 11:25 UTC, jrhender requested changes
Minor point, but I think we should use the `chore` or `docs` commit prefix as I don't think there are any functional features involved in this PR.

2022-11-16 11:45 UTC, artursudnik commented
@jrhender Good point. I'll squash merge and use `chore` in the commit message

2022-11-21 08:20 UTC, jrhender approved these changes

2022-11-21 10:17 UTC, nichonien approved these changes

2022-11-21 10:26 UTC, merged