chore: adding gp4btc swagger hostnames to allowed origins
energywebfoundation/ssi-hub pull request #608
Opened 2023-03-15 12:22 UTC by artursudnik

This PR fixes the issue with requests sent from the Swagger interface are forbidden server-side

2023-03-15 13:14 UTC, JGiter approved these changes

2023-03-15 13:46 UTC, jrhender approved these changes

2023-03-15 13:49 UTC, jrhender requested changes

2023-03-15 13:49 UTC, jrhender commented on devops/prod/values.yaml
> +    ALLOWED_ORIGINS: https://identitycache-gp4btc.energyweb.org,https://switchboard.energyweb.org,https://consortia-stake-ewt.io,https://green.stake-ewt.io,https://greenpool.stake-ewt.io,https://crow
```suggestion
    ALLOWED_ORIGINS: https://identitycache.energyweb.org,https://switchboard.energyweb.org,https://consortia-stake-ewt.io,https://green.stake-ewt.io,https://greenpool.stake-ewt.io,https://crowdfund4solar.com
```

2023-03-23 09:11 UTC, jrhender approved these changes

2023-03-23 11:22 UTC, merged